name: Build and Commit File

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install
        run: |
          npm ci

      - name: Build Radar
        run: |
          npm run radar

      - uses: actions/upload-artifact@v2
        with:
          name: radar-output
          path: radar.json


  commit:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: radar-output
      - run: git checkout -b commit-branch
      - run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add radar.json
          git commit -m "Automatic commit from workflow"
      - run: git push origin radar-branch